export const jobsObj = [
  {
    name: 'Desarrollador Front End',
    image: 'FrontEnd.png',
    FuncionesConocimientos:
      'Este candidato tiene la capacidad  de trabajar con un equipo técnico altamente energizado,  Tiene una sólida comprensión de la gestión de dependencias de código, análisis de casos de prueba y configuración de contenedores, registro y análisis.',
    SoftSkills: [
      'Trabajo en equipo',
      'Proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: [
      'Javascript, React',
      'Typescript',
      'CSS',
      'SASS',
      'NodeJS',
      'ES6',
      'HMTL 5',
      'GIT',
      'Jquery',
      'Booststrap',
      'ES6',
      'Alto conocimiento en eCommerce y construcción de sistemas empresariales.',
    ],
  },
  {
    name: 'Desarrollador Back End',
    image: 'BackEnd.png',
    FuncionesConocimientos:
      'Este candidato tiene la capacidad  de trabajar con un equipo técnico altamente energizado,  Tiene una sólida comprensión de la gestión de dependencias de código, análisis de casos de prueba y configuración de contenedores, registro y análisis.',
    SoftSkills: [
      'Trabajo en equipo, proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: [
      'java',
      'core net',
      '.Net',
      'python 3.6',
      'C#',
      '.Net 4.5 o superior',
      '.Net Core 3.1 o superior',
      'spring boot',
      'spring batch',
      'spring security',
      'JPA',
      'sql server',
      'lambdas AWS',
      'S3',
      'api gateway',
      'cloudwatch',
      'Lambda',
      'Triggers',
      'Funciones',
      'Manejo de Java 1.8 o superior',
      'conocimiento de paradigma de programación en microservicios',
      'Python',
      'dockers (contenedores, pods, clusters, uso de entornos serverless, conocimientos de CI/CD)',
      'desarrolló en ambientes cloud (GCP, AWS, Azure, etc)',
      'Alto conocimiento en eCommerce',
    ],
  },
  {
    name: 'Project Manager',
    image: 'PMO.png',
    FuncionesConocimientos:
      'En otras palabras, es el perfil que coordina el trabajo del equipo para cumplir con los objetivos. Tiene la capacidad de planeación, organización, coordinación y control de trabajo. Alto conocimiento en retail, eCommerce y omnicanalidad.',
    SoftSkills: [
      'Trabajo en equipo',
      'Liderazgo, proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: ['Jira', 'Excel avanzado', 'Proyect', 'PPT'],
  },
  {
    name: 'Business Intelligence',
    image: 'ProductManager.png',
    FuncionesConocimientos:
      'Es el profesional encargado tanto de la recopilación como del análisis de información y datos de ventas, mercados, consumidores, etc., con la finalidad de facilitar la toma de decisiones operacionales o estratégicas más adecuadas para lograr los objetivos de la empresa. La obtención de la información es únicamente una parte de su trabajo, puesto que el verdadero valor para la organización se encuentra en su posterior análisis y procesamiento.',
    SoftSkills: [
      'Liderazgo, proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: ['Data Discovery applications','Herramientas para gestión de datos',  'herramienta de reporting'],
  },
  {
    name: 'Head Técnico',
    image: 'QA.png',
    FuncionesConocimientos:
      'El rol de Head técnico de células tiene responsabilidades, técnicas, orientación y propuesta de mejores prácticas tecnológicas así como brindar soluciones de clase mundial a los clientes donde se encuentre instalada una célula de vinnenen con los clientes.',
    SoftSkills: [
      'Trabajo en equipo',
      'Liderazgo',
      'proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto, alto sentido de resultados',
    ],
    TechSkills: [
      'Javascript',
      'React',
      'Typescript',
      'CSS',
      'SASS',
      'NodeJS',
      'ES6',
      'HMTL 5',
      'GIT',
      'Jquery',
      'Booststrap',
      'ES6',
    ],
  },
  {
    name: 'Scrum Master',
    image: 'ScrumMaster.png',
    FuncionesConocimientos:
      'Es responsabilidad del Administrador de proyectos asegurar que el alcance del trabajo se realice con calidad, dentro del presupuesto y a tiempo, para que el cliente quede satisfecho. Su responsabilidad principal es proporcionar liderazgo en la planeación, organización y control del esfuerzo del trabajo para lograr el objetivo establecido.',

    SoftSkills: [
      'Trabajo en equipo',
      'proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto, alto sentido de resultados',
    ],
    TechSkills: [],
  },
  {
    name: 'Diseñador UX',
    image: 'UXSenior.png',
    FuncionesConocimientos:
      'Nuestros equipos de UX aspiran a crear productos que la gente ame: herramientas que hagan que el día de un vendedor sea más productivo, que la campaña de un vendedor sea más poderosa o que la aplicación de un desarrollador tenga más funciones. ',
    SoftSkills: [
      'Trabajo en equipo',
      'proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: [],
  },
  {
    name: 'DigiOps',
    image: 'PMO.png',
    FuncionesConocimientos:
      'El desarrollo del puesto ayudará a las demás áreas del equipo y al cliente a resolver temas relacionados con la funcionalidad de los ambientes.',
    SoftSkills: [
      'Trabajo en equipo',
      'Multitask (trabajo con diferentes clientes al mismo tiempo)',
      'Razonamiento Lógico',
      'Autodidacta',
      'Customer Service',
      'Customer Experience',
      'Buenas prácticas sobre contenido de producto',
    ],
    TechSkills: [
      'Conocimiento de la plataforma Vtex (preferente)',
      'Conocimiento de ecommerce',
      'Conocimiento en Google Analytics y Tag Manager',
      'Excel básico',
      'Conocimiento básico de SEO',
    ],
  },
]
