export const jobsObj = [
  {
    name: 'Desarrollador Front End',
    FuncionesConocimientos: '',
    SoftSkills: [
      'Trabajo en equipo',
      'Proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: [
      'Javascript',
      'React',
      'Typescript',
      'CSS',
      'SASS',
      'NodeJS',
      'ES6',
      'HMTL 5',
      'GIT',
      'Jquery',
      'Booststrap',
      'ES6',
      'Alto conocimiento en eCommerce y construcción de sistemas empresariales.',
    ],
  },
  {
    name: 'Desarrollador Back End',
    FuncionesConocimientos: '',
    SoftSkills: [
      'Trabajo en equipo, proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: [
      'java',
      'core net',
      '.Net',
      'python 3.6',
      'C#',
      '.Net 4.5 o superior',
      '.Net Core 3.1 o superior',
      'spring boot',
      'spring batch',
      'spring security',
      'JPA',
      'sql server',
      'lambdas AWS',
      'S3',
      'api gateway',
      'cloudwatch',
      'Lambda',
      'Triggers',
      'Funciones',
      'Manejo de Java 1.8 o superior',
      'conocimiento de paradigma de programación en microservicios',
      'Python',
      'dockers (contenedores, pods, clusters, uso de entornos serverless, conocimientos de CI/CD)',
      'desarrolló en ambientes cloud (GCP, AWS, Azure, etc)',
      'Alto conocimiento en eCommerce',
    ],
  },
  {
    name: 'Project Manager',
    FuncionesConocimientos: '',
    SoftSkills: [
      'Trabajo en equipo',
      'Liderazgo, proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: ['Jira', 'Excel avanzado', 'Proyect', 'PPT'],
  },
  {
    name: 'Product Manager',
    FuncionesConocimientos:
      "Jira , Excel avanzado, Proyect, PPT Excelentes habilidades organizativas, analíticas y de comunicación y atención al detalle. Capacidad comprobada para influir en equipos multifuncionales sin autoridad formal. Capacidad comprobada para crear requisitos/diseños funcionales, esquemas, demostraciones de productos y pruebas de conceptos para nuevas ideas de productos y eventos de marketing. Conocimiento práctico de la tecnología web front-end moderna, incluidos HTML, javascript, React y CSS Profesionalismo, dedicación y capacidad para trabajar en un entorno de equipo colaborativo. Es muy importante tener ojo para los detalles, así como un gran instinto de diseño, habiendo trabajado en estrecha colaboración con UX para crear grandes experiencias en el pasado. Capacidad para priorizar y decir cortésmente 'No' a una letanía de buenas ideas que distraen a su equipo de trabajar en grandes ideas. Con conocimientos en tecnologías, plataformas de colaboración.",
    SoftSkills: [
      'Trabajo en equipo',
      'Liderazgo, proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: [],
  },
  {
    name: 'Sales Rep',
    FuncionesConocimientos:
      'Experiencia en ventas, preferiblemente dentro de una organización,experiencia en gestión de ventas,comprensión sólida de las aplicaciones y la tecnología de colaboración, Historial consistente de venta de software en cuentas comerciales y logro de objetivos personales y de equipo, Capacidad para hacer crecer el negocio de manera estratégica, incluida la generación de demanda, Excelentes habilidades de coaching, escritura, descubrimiento y presentación, Historia de prosperar en un entorno que cambia rápidamente, Entusiasmo por aumentar la felicidad del cliente y profundizar las relaciones con los clientes, Cómodo y dispuesto a ser un colaborador práctico, Licenciatura requerida.',
    SoftSkills: [
      'Trabajo en equipo',
      'Liderazgo, proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
      'apasionado en ventas',
      'negociación y planteamiento de Fases de trabajo',
    ],
    TechSkills: [],
  },
  {
    name: 'Head Técnico',
    FuncionesConocimientos: '',
    SoftSkills: [
      'Trabajo en equipo',
      'Liderazgo',
      'proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: [
      'Javascript',
      'React',
      'Typescript',
      'CSS',
      'SASS',
      'NodeJS',
      'ES6',
      'HMTL 5',
      'GIT',
      'Jquery',
      'Booststrap',
      'ES6',
      'Despliegue de funcionalidades mediante integración con sistemas backend',
      'alto conocimiento en eCommerce y construcción de sistemas empresariales',
    ],
  },
  {
    name: 'Quality Assurance',
    FuncionesConocimientos: '',
    SoftSkills: [
      'Trabajo en equipo',
      'proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: [
      'Diseño y creación de herramientas de Software que permitan probar las funcionalidades y certificar la calidad de los productos generadas por el área de desarrollo de la empresa',
      'Preparación de ambientes para verificación de los productos desarrollados',
      'Generación de procesos que permitan probar rápida y confiablemente las plataformas desarrolladas por la empresa (automatización)',
      'Alta interacción con áreas de Desarrollo y Soporte de la empresa y con los clientes',
      'Instalación de las aplicaciones en los ambientes de producción del cliente',
      'Asegurar que el producto se desarrolle correctamente y debe comprobar que se cumplen las expectativas del usuario que va a utilizar dicho producto',
      'Plan de pruebas, gestionar los riesgos',
      'definir los criterios de aceptación',
      'gestionar defectos y pruebas exploratoria',
      'Pruebas de regresión y análisis de código',
      'Fundamental saber el estado en el que se encuentra cada tarea del proyecto en cada momento',
    ],
  },
  {
    name: 'Scrum Master',
    FuncionesConocimientos: [
      'Entre las funciones más relevantes de un Scrum Master se encuentran:',
      '● Análisis de los proyectos a su cargo (tiempo, alcance y calidad)',
      '● Estimar los recursos y los plazos necesarios',
      '● Manejo y administración del equipo de trabajo y recursos para lograr los objetivos del proyecto en los plazos acordados',
      '● *Aplicar procesos de gestión de proyectos (Agile), para planificar, ejecutar, supervisar, controlar y cerrar proyectos *',
      '● * Dirigir y motivar al equipo mediante la implementación y ejecución de las mejores prácticas de la administración de proyectos (SCRUM)*',
      '● Gestionar las sesiones necesarias de seguimiento, control y avances para la ejecución del proyecto.',
      '● Gestión y control de riesgos, problemas y cambios que puedan haber en el proyecto',
      '● Mantener una comunicación continua con los stakeholders.',
    ],
    SoftSkills: [
      'Trabajo en equipo',
      'proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto, alto sentido de resultados',
    ],
    TechSkills: [],
  },
  {
    name: 'Monitoring',
    FuncionesConocimientos:
      'Monitorear que los servidores estén funcionando acorde a los umbrales establecidos, monitorear que los procesos, apis, sistemas operen de manera adecuada. Realizar actividades de troubleshooting y escalar aquellas que sean requeridas. Realizar reporte de incidentes diario y de status de los recursos informáticos que se están monitoreando',
    SoftSkills: [
      'Trabajo en equipo',
      'proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: [],
  },
  {
    name: 'Full Stack',
    FuncionesConocimientos:
      'Desarrolle componentes basados en la interfaz de usuario en diseños o maquetas proporcionados, Desarrollar componentes de interfaz de usuario que pueden ser personalizados por el cliente a través del Editor del sitio VTEX, Código impulsado por el rendimiento, la calidad y el SEO asegurarse de que su código funcione en todos los navegadores y dispositivos requeridos, Mantener actualizada la documentación del proyecto. Flujo de trabajo durante todo el proceso de desarrollo, apoyar al equipo de control de calidad durante el proceso de prueba.',
    SoftSkills: [
      'Trabajo en equipo',
      'proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto, alto sentido de resultados',
    ],
    TechSkills: [],
  },
  {
    name: 'Diseñador UX Senior',
    FuncionesConocimientos:
      'Experiencia en el diseño y la entrega de productos de principio a fin como parte de un equipo multifuncional, Capacidad para administrar con éxito todos los aspectos de un proyecto de principio a fin, trabajando con miembros del equipo distribuidos y en el sitio para garantizar la entrega del proyecto a tiempo, Automotivación; capacidad para producir resultados de forma independiente y como parte de un equipo, Habilidad para transmitir claramente y seguir instrucciones, Capacidad para crear y entregar rápidamente un trabajo de diseño original y de calidad profesional que sea conceptualmente sólido, satisfaga las necesidades comerciales y esté en la marca y en breve, Comprensión experta de métodos y prácticas de diseño centrados en el usuario Experiencia en el uso de múltiples enfoques, incluidos análisis e investigación de usuarios, para impulsar decisiones y desarrollar iteraciones de productos, Conocimiento experto de las herramientas de diseño actuales, como Figma, junto con la capacidad de aprender rápidamente nuevas herramientas a medida que surgen, Habilidad para comunicar ideas a una amplia variedad de partes interesadas, liderar debates y actividades creativas, y generar consenso mientras se enfrenta a la ambigüedad. Habilidad para liderar y administrar grandes iniciativas de diseño, incluida la gestión de prioridades contrapuestas con colegas de ingeniería y productos.',
    SoftSkills: [
      'Trabajo en equipo',
      'proactividad',
      'buena organización y de trabajo bajo presión',
      'excelente comunicación',
      'capacidades analíticas y de resolución de problemas',
      'paciencia y perseverancia para resolver problemas',
      'capacidad de gestión de conflicto',
      'alto sentido de resultados',
    ],
    TechSkills: [],
  },
  {
    name: 'Becarios',
    FuncionesConocimientos:
      'Este rol brinda la oportunidad de trabajar con un equipo técnico de alto rendimiento. Podrá forjarse como excelente ingeniero entendiendo todas las fases del ciclo de vida de software. El equipo de ingeniería de Vinneren está innovando rápidamente en el espacio de TI y mejorando la productividad de los desarrolladores desde el código en la nube. Se parte del equipo dinámico Si ha sido un tecnólogo de vanguardia y le ha apasionado mejorar la productividad de los desarrolladores ¡entonces este es el equipo para ti!',
    SoftSkills: [],
    TechSkills: [],
  },
  {
    name: 'DigiOps',
    FuncionesConocimientos:
      'El desarrollo del puesto ayudará a las demás áreas del equipo y a el cliente a resolver temas relacionados con la funcionalidad de los ambientes.',
    SoftSkills: [
      'Trabajo en equipo',
      'Multitask (trabajo con diferentes clientes al mismo tiempo)',
      'Razonamiento Lógico',
      'Autodidacta',
      'Customer Service',
      'Customer Experience',
      'Buenas prácticas sobre contenido de producto',
    ],
    TechSkills: [
      'Conocimiento de la plataforma Vtex (preferente)',
      'Conocimiento de ecommerce',
      'Conocimiento en Google Analytics y Tag Manager',
      'Excel básico',
      'Conocimiento básico de SEO',
    ],
  },
]
